name: Deploy
on:
  push:
    branches-ignore:
      - 'no-ci-**'
      - 'skip-ci-**'
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

env:
  # common settings
  CMAKE_VERSION: 3.21.x
  # paths
  ci_native_sdk_name: rebelfork-sdk-Linux-clang-rel-dll-x64-latest.zip
  ci_target_sdk_name: rebelfork-sdk-Web-rel-lib-latest.zip
  ci_source_dir: ${{ github.workspace }}/source-code
  ci_build_script: ./source-code/Script/ci_build.sh
  ci_build_dir: ${{ github.workspace }}/cmake-build
  ci_native_sdk_dir: ${{ github.workspace }}/SDK-native
  ci_target_sdk_dir: ${{ github.workspace }}/SDK-target

jobs:
  CheckSkipCI:
    runs-on: ubuntu-20.04
    if: |
      !contains(github.event.head_commit.message, '[skip ci]') &&
      !contains(github.event.pull_request.title, '[skip ci]') &&
      !contains(github.event.head_commit.message, '[skip-ci]') &&
      !contains(github.event.pull_request.title, '[skip-ci]')
    steps:
      - run: exit 0

  Web:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-20.04
    needs: [CheckSkipCI]

    strategy:
      fail-fast: false
      matrix:
        ci_emsdk_version:
          - latest
        ci_build_mode:
          - sdk
          - subdirectory

    env:
      ci_build_mode: ${{ matrix.ci_build_mode }}
      ci_publish: ${{ github.ref == 'refs/heads/master' && github.repository == 'rbfx/sample-project' && matrix.ci_build_mode == 'sdk'}}
      BINARYEN_CORES: 1

    steps:
      - uses: mymindstorm/setup-emsdk@v11
        with:
          version: ${{ matrix.ci_emsdk_version }}

      - name: Checkout Sample Project
        uses: actions/checkout@v2
        with:
          path: ${{ env.ci_source_dir }}
          fetch-depth: 1
          submodules: true

      - name: Checkout the Framework
        if: ${{ matrix.ci_build_mode == 'subdirectory' }}
        uses: actions/checkout@v2
        with:
          repository: rbfx/rbfx
          path: ${{ env.ci_source_dir }}/../rbfx
          fetch-depth: 1
          submodules: true

      - name: Download native SDK
        uses: robinraju/release-downloader@v1.8
        with:
          repository: rbfx/rbfx
          tag: latest
          fileName: ${{ env.ci_native_sdk_name }}

      - name: Unzip native SDK
        run: |
          cd ${{ github.workspace }}
          unzip ${{ env.ci_native_sdk_name }}
          mv ./SDK ./SDK-native

      - name: Download target SDK
        if: ${{ matrix.ci_build_mode == 'sdk' }}
        uses: robinraju/release-downloader@v1.8
        with:
          repository: rbfx/rbfx
          tag: latest
          fileName: ${{ env.ci_target_sdk_name }}

      - name: Unzip target SDK
        if: ${{ matrix.ci_build_mode == 'sdk' }}
        run: |
          cd ${{ github.workspace }}
          unzip ${{ env.ci_target_sdk_name }}
          mv ./SDK ./SDK-target

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '${{ env.CMAKE_VERSION }}'

      - name: Dependencies
        shell: bash
        run: ${{ env.ci_build_script }} dependencies

      - name: Generate
        shell: bash
        run: ${{ env.ci_build_script }} generate

      - name: Build
        shell: bash
        run: ${{ env.ci_build_script }} build

      - name: Prepare
        shell: bash
        run: ${{ env.ci_build_script }} prepare

      - name: Publish
        if: ${{ env.ci_publish }}
        uses: KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{ secrets.BUTLER_API_KEY }}
          gameData: ${{ github.workspace }}/cmake-build/bin/project
          itchUsername: eugeneko
          itchGameId: sample-project
          buildChannel: web
